"""Markdown exporter — human-readable transcript with time-block headers."""

from __future__ import annotations

import logging
from pathlib import Path

from voxscribe._utils import format_timestamp_hms
from voxscribe.models import MergedSegment

logger = logging.getLogger(__name__)


class MarkdownExporter:
    """Exports transcript as a structured Markdown document.

    Segments are grouped into configurable time blocks (default: 1 minute).
    Each block has a header showing its time range; within each block,
    segments are rendered as ``**SPEAKER** [HH:MM:SS]: text``.

    When a summary is provided (from the Ollama summarizer), it is appended
    as a dedicated *Summary* section at the bottom of the document.

    Example output::

        # Interview — 2024-11-15

        **Duration:** 00:45:12
        **Speakers:** SPEAKER_00, SPEAKER_01

        ---

        ## 00:00:00 – 00:01:00

        **SPEAKER_00** `[00:00:04]`: Hello and welcome to the show.

        **SPEAKER_01** `[00:00:07]`: Thanks for having me.

        ---
        *Generated by VoxScribe*
    """

    def __init__(self, block_minutes: int = 1) -> None:
        """
        Args:
            block_minutes: Duration of each time block in minutes.
        """
        self.block_minutes = block_minutes

    def export(
        self,
        segments: list[MergedSegment],
        output_path: Path,
        *,
        title: str | None = None,
        summary: str | None = None,
    ) -> None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        blocks = self._group_by_blocks(segments)
        duration = segments[-1].end if segments else 0.0
        speakers = sorted({s.speaker for s in segments})
        doc_title = title or output_path.stem

        with output_path.open("w", encoding="utf-8") as f:
            # ── Header ────────────────────────────────────────────────────
            f.write(f"# {doc_title}\n\n")
            f.write(f"**Duration:** {format_timestamp_hms(duration)}  \n")
            f.write(f"**Speakers:** {', '.join(speakers)}\n\n")
            f.write("---\n\n")

            # ── Time blocks ───────────────────────────────────────────────
            for block_idx in sorted(blocks):
                block_start_s = block_idx * self.block_minutes * 60
                block_end_s = block_start_s + self.block_minutes * 60
                f.write(
                    f"## {format_timestamp_hms(block_start_s)} – "
                    f"{format_timestamp_hms(block_end_s)}\n\n"
                )
                for seg in blocks[block_idx]:
                    ts = format_timestamp_hms(seg.start)
                    f.write(f"**{seg.speaker}** `[{ts}]`: {seg.text.strip()}\n\n")

            # ── Summary (optional) ────────────────────────────────────────
            if summary:
                f.write("---\n\n")
                f.write("## Summary\n\n")
                f.write(summary.strip())
                f.write("\n\n")

            # ── Footer ────────────────────────────────────────────────────
            f.write("---\n\n")
            f.write("*Generated by [VoxScribe](https://github.com/JuanLara18/voxscribe)*\n")

        logger.info("Markdown written → %s", output_path)

    # ── Internals ─────────────────────────────────────────────────────────

    def _group_by_blocks(
        self, segments: list[MergedSegment]
    ) -> dict[int, list[MergedSegment]]:
        blocks: dict[int, list[MergedSegment]] = {}
        block_secs = self.block_minutes * 60

        for seg in segments:
            idx = int(seg.start // block_secs)
            blocks.setdefault(idx, []).append(seg)

        # Ensure segments within each block are time-ordered.
        for blk in blocks.values():
            blk.sort(key=lambda s: s.start)

        return blocks
